### ISSUE TITLE
Add font support Vietnamese

### ISSUE THREAD

**Issue by lelinhtinh** [lelinhtinh/jEpub#1]
[Open Sans](https://fonts.google.com/specimen/Open+Sans)?

**Comment by huntermad** [comment]
Trừ phần thường thấy như Dấu"hỏi" bị mất 1 phần khi dùng chữ viết hoa bình thường thì rất rốt . Dùng cho titile thì không vấn đề gì( BOLD với ITALIC Thì vẫn thấy rõ dấu)
