### ISSUE TITLE
Type definition file

### ISSUE THREAD

**Issue by P0oOOOo0YA** [lelinhtinh/jEpub#12]
Hi folks, Is there any plan to provide a type definition file for this package?

**Comment by lelinhtinh** [comment]
Have a plan right now, can you help me?

**Comment by P0oOOOo0YA** [comment]
@lelinhtinh  Apologies for the Late Reply, Hope you plan to rewrite the whole project in typescript:)

**Comment by carlsonsantana** [comment]
> Have a plan right now, can you help me?

Do you still need help?
