### ISSUE TITLE
Unable to use in Project

### ISSUE THREAD

**Issue by fameoflight** [lelinhtinh/jEpub#15]
When doing import I am running into ./node_modules/jepub/src/jepub.js
`Module not found: Can't resolve './tpl/OEBPS/front-cover.html' in '/Users/hemantv/workspace/tellado/tellado-webapp/node_modules/jepub/src' `

any ideas what might be going on here?

**Comment by lelinhtinh** [comment]
Actually, I've never run this project in a nodejs environment. 😳 

Importing from the dist directory will [work](https://codesandbox.io/s/7thjk):
```js
import jEpub from "./node_modules/jepub/dist/jepub.js";
```
