### ISSUE TITLE
images in content

### ISSUE THREAD

**Issue by njacob1001** [lelinhtinh/jEpub#2]
Hello, how to add a <im> or what is the way for add images in a section content?

**Comment by lelinhtinh** [comment]
No way, at this time.

**Comment by njacob1001** [comment]
But, do you know how can I insert something like this?
![screen](https://i.imgur.com/zteUAPZ.png)

**Comment by lelinhtinh** [comment]
You can try this guide: https://manual.calibre-ebook.com/edit.html

**Comment by lelinhtinh** [comment]
@njacob1001 Please see [this example](https://github.com/lelinhtinh/jEpub/blob/ce2341c96dde9d32125ca07d37434b06ba57807b/demo/script.js#L22-L33) of using [.image()](https://github.com/lelinhtinh/jEpub#add-image) method.
