### ISSUE TITLE
The table of contents is titled "Mục lục"

### ISSUE THREAD

**Issue by cosmin-novac** [lelinhtinh/jEpub#24]
Is there a way to change it?

**Comment by cosmin-novac** [comment]
I found the reason. The default internationalization was not 'en'. It was an easy fix.

**Comment by lelinhtinh** [comment]
As of v2.1.4, the default value of `i18n` is `en`.

**Comment by cosmin-novac** [comment]
However, the init is still in `vi`

`   init(details) {
        this._Info = Object.assign({}, {
            i18n: 'vi',`

**Comment by lelinhtinh** [comment]
I don't know why, I [changed it](https://github.com/lelinhtinh/jEpub/commit/f649633845c1463b7486d2810298a65e78c0be3c) before v2.1.4 was released.
